sub_enum_tools:
  subfinder: "subfinder -silent -d {domain}"
  amass: "amass enum -passive -d {domain}"
  assetfinder: "assetfinder --subs-only {domain}"

tools:
  httpx: "httpx -silent -status-code -title -tech-detect"
  nmap_quick: "nmap -T4 -Pn -n -p 1-1000"
  nmap_full: "nmap -T4 -Pn -n -p-"
  nuclei: "nuclei -silent -severity critical,high,medium"
  eyewitness: "eyewitness --web -f {file} -d {outdir} --timeout 10 --no-prompt"
  whatweb: "whatweb --input-file={file} --aggression=3 --log-verbose={outfile}"

paths:
  subdomain_output: "results/subdomains"
  alive_output: "results/alive"
  scan_output: "results/scans"
  screenshot_output: "results/screenshots"
  tech_output: "results/tech"


notify:
  enabled: false
  telegram:
    token: "YOUR_BOT_TOKEN_HERE"
    chat_id: "YOUR_CHAT_ID_HERE"
